parameters:
  database_host: 127.0.0.1
  database_port: 3306
  database_name: project_dev
  database_user: root
  database_password: password
  database_host_test: 127.0.0.1
  database_port_test: 3306
  database_name_test: project_dev_test
  database_user_test: root
  database_password_test: password